name: Scheduled Beat Plan Report

on:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
    - cron: '30 10 * * *'   # 4:00 PM IST
    - cron: '30 11 * * *'  # 5:00 PM IST


jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tableauserverclient

      - name: Run Beat Plan Script
        env:
          TABLEAU_TOKEN: ${{ secrets.TABLEAU_TOKEN }}
        run: python master_runner.py
